"""Initial migration

Revision ID: aa939cd140e4
Revises: 
Create Date: 2024-12-01 11:40:29.800479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa939cd140e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('NER', 'NLU', name='modeltype'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('train_data_count', sa.Integer(), nullable=False),
    sa.Column('test_data_count', sa.Integer(), nullable=False),
    sa.Column('training_time', sa.Float(), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('batch_size_min', sa.Float(), nullable=False),
    sa.Column('batch_size_max', sa.Float(), nullable=False),
    sa.Column('dropout_rate', sa.Float(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('optimizer', sa.String(length=50), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('departure_precision', sa.Float(), nullable=True),
    sa.Column('departure_recall', sa.Float(), nullable=True),
    sa.Column('departure_f1', sa.Float(), nullable=True),
    sa.Column('departure_support', sa.Integer(), nullable=True),
    sa.Column('arrival_precision', sa.Float(), nullable=True),
    sa.Column('arrival_recall', sa.Float(), nullable=True),
    sa.Column('arrival_f1', sa.Float(), nullable=True),
    sa.Column('arrival_support', sa.Integer(), nullable=True),
    sa.Column('confusion_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('is_treated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sentences')
    op.drop_table('ml_models')
    op.drop_table('cities')
    # ### end Alembic commands ###
